#!/usr/bin/env python3
"""Build script: converts markdown posts in posts/ to HTML in blog/

Usage: python3 build.py
Requires: pip install -r requirements.txt
"""

import datetime
import re
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import mdformat
    import markdown
    import yaml
    from l2m4m import LaTeX2MathMLExtension
except ImportError:
    print("Missing dependencies. Run: pip install -r requirements.txt", file=sys.stderr)
    sys.exit(1)

from tooltip import TooltipExtension, preserve_tooltips, restore_tooltips, add_tooltip_footnotes
from rss import build_feed

ROOT = Path(__file__).parent
POSTS_DIR = ROOT / "posts"
BLOG_DIR = ROOT / "blog"
POSTS_LIST = POSTS_DIR / "posts.txt"

POST_TEMPLATE = """\
<!-- THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{POST_TITLE}} - Sam Xifaras</title>
    <link rel="stylesheet" href="../styles.css">
    <link rel="stylesheet" href="../blog.css">
    <script src="../theme.js"></script>
    <script src="../analytics.js"></script>
</head>
<body>
    <main>
        <div class="container">
            <a href="../feed.xml" class="rss-corner" title="RSS Feed" aria-label="RSS Feed"><img src="../rssicon.svg" width="24" height="24" alt="RSS Feed"></a>
            <nav class="blog-nav">
                <a href="../index.html">Home</a>
                <span class="blog-nav-sep">/</span>
                <a href="index.html">Blog</a>
            </nav>
            <div class="theme-switcher">
                <button class="theme-btn" data-theme="normal">Normal</button>
                <button class="theme-btn" data-theme="sepia">Sepia</button>
                <button class="theme-btn" data-theme="dark">Dark</button>
            </div>
            <article class="post">
                <header class="post-header">
                    <h1>{{POST_TITLE}}</h1>
                    <time class="post-date" datetime="{{POST_DATE_ISO}}">{{POST_DATE_DISPLAY}}</time>
                </header>
                <div class="post-body">
                    {{POST_BODY}}
                </div>
            </article>
        </div>
    </main>
    <footer>
        <div class="newsletter">
            <p class="newsletter-label">Want to get updates from me? Drop your email below!</p>
            <form id="newsletter-form" class="newsletter-form">
                <input type="email" id="newsletter-email" placeholder="your@email.com" required>
                <button type="submit">Subscribe</button>
            </form>
            <p id="newsletter-msg" class="newsletter-msg"></p>
        </div>
        <p class="footer-copyright">&copy; 2026 Samuel Xifaras</p>
    </footer>
</body>
</html>"""

INDEX_TEMPLATE = """\
<!-- THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - Sam Xifaras</title>
    <link rel="stylesheet" href="../styles.css">
    <link rel="stylesheet" href="../blog.css">
    <script src="../theme.js"></script>
    <script src="../analytics.js"></script>
</head>
<body>
    <main>
        <div class="container">
            <a href="../feed.xml" class="rss-corner" title="RSS Feed" aria-label="RSS Feed"><img src="../rssicon.svg" width="24" height="24" alt="RSS Feed"></a>
            <nav class="blog-nav">
                <a href="../index.html">Home</a>
                <span class="blog-nav-sep">/</span>
                <span>Blog</span>
            </nav>
            <div class="theme-switcher">
                <button class="theme-btn" data-theme="normal">Normal</button>
                <button class="theme-btn" data-theme="sepia">Sepia</button>
                <button class="theme-btn" data-theme="dark">Dark</button>
            </div>
            <section class="blog-index">
                <i id="expressions">Expressions of my inner world</i>
                <h2>Blog</h2>
                <div class="category-filters">
                    <button class="filter-btn active" data-filter="all">All</button>
                    <button class="filter-btn" data-filter="blog" data-tip="Longer-form, more heavily researched content.">Blog</button>
                    <button class="filter-btn" data-filter="thoughts" data-tip="Quick, unedited streams of consciousness.">Thoughts</button>
                    <button class="filter-btn" data-filter="poetry" data-tip="Self-explanatory.">Poetry</button>
                </div>
                {{POST_LIST}}
            </section>
        </div>
    </main>
    <footer>
        <div class="newsletter">
            <p class="newsletter-label">Want to get updates from me? Drop your email below!</p>
            <form id="newsletter-form" class="newsletter-form">
                <input type="email" id="newsletter-email" placeholder="your@email.com" required>
                <button type="submit">Subscribe</button>
            </form>
            <p id="newsletter-msg" class="newsletter-msg"></p>
        </div>
        <p class="footer-copyright">&copy; 2026 Samuel Xifaras</p>
    </footer>
    <script src="../filters.js"></script>
</body>
</html>"""


@dataclass
class PostData:
    title: str
    date: datetime.date
    description: str
    slug: str
    html_body: str
    category: str = "blog"


def format_date(d: datetime.date) -> str:
    """Return a human-readable date like 'March 21, 2026'."""
    return d.strftime("%B {day}, %Y").format(day=d.day)


def parse_post(path: Path) -> PostData:
    content = path.read_text(encoding="utf-8")
    parts = content.split("---", 2)
    if len(parts) == 3 and parts[0].strip() == "":
        meta = yaml.safe_load(parts[1]) or {}
        body = parts[2]
    else:
        meta = {}
        body = content

    slug = path.stem
    title = meta.get("title", slug.replace("-", " ").title())
    description = meta.get("description", "")
    category = meta.get("category", "blog")

    raw_date = meta.get("date", "")
    if isinstance(raw_date, datetime.date):
        date = raw_date
    elif raw_date:
        date = datetime.date.fromisoformat(str(raw_date))
    else:
        date = datetime.date.today()

    md = markdown.Markdown(extensions=["fenced_code", "tables", LaTeX2MathMLExtension(), TooltipExtension()])
    html_body = add_tooltip_footnotes(md.convert(body))

    return PostData(
        title=title,
        date=date,
        description=description,
        slug=slug,
        html_body=html_body,
        category=category,
    )


def render_post_html(post: PostData) -> str:
    return (
        POST_TEMPLATE
        .replace("{{POST_TITLE}}", post.title)
        .replace("{{POST_DATE_ISO}}", post.date.isoformat())
        .replace("{{POST_DATE_DISPLAY}}", format_date(post.date))
        .replace("{{POST_BODY}}", post.html_body)
    )


def render_index_html(posts: list) -> str:
    if not posts:
        post_list = "<p>No posts yet.</p>"
    else:
        entries = []
        for post in posts:
            description_html = (
                f'<p class="post-description">{post.description}</p>'
                if post.description
                else ""
            )
            entries.append(
                f'<article class="post-listing" data-category="{post.category}">\n'
                f'    <h3><a href="{post.slug}.html">{post.title}</a></h3>\n'
                f'    <div class="post-meta">'
                f'<time class="post-date" datetime="{post.date.isoformat()}">'
                f'{format_date(post.date)}</time>'
                f'<span class="post-category">{post.category}</span>'
                f'</div>\n'
                f'    {description_html}\n'
                f'</article>'
            )
        post_list = "\n".join(entries)

    return INDEX_TEMPLATE.replace("{{POST_LIST}}", post_list)


def get_post_files() -> list[Path]:
    """Return the list of post files to build, as specified in posts/posts.txt."""
    lines = POSTS_LIST.read_text(encoding="utf-8").splitlines()
    paths = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name = line if line.endswith(".md") else f"{line}.md"
        path = POSTS_DIR / name
        if path.exists():
            paths.append(path)
        else:
            print(f"  Warning: {name} listed in posts.txt but not found", file=sys.stderr)
    return paths


def format_posts():
    for md_file in sorted(get_post_files()):
        # Extract frontmatter if present, remove before formatting, and re-add after
        text = md_file.read_text(encoding="utf-8")
        match = re.match(r"^---\s*\n(.*?)(?:^---\s*$\n?)", text, re.DOTALL | re.MULTILINE)
        if match:
            frontmatter = match.group(0)
            body = text[len(frontmatter):]
            # Remove any leading newlines after the frontmatter block
            body = body.lstrip('\r\n')
        else:
            frontmatter = ""
            body = text

        tooltip_map = {}
        body = preserve_tooltips(body, tooltip_map)

        latex_map = {}
        def replace_latex(m):
            key = f"XLATEX{len(latex_map)}X"
            latex_map[key] = m.group(0)
            return key
        body = re.sub(r'\$\$[\s\S]*?\$\$|\$[^$\n]+?\$', replace_latex, body, flags=re.MULTILINE)

        dollar_placeholder = "XDOLLARENTITYX"
        body = body.replace("&dollar;", dollar_placeholder)

        tmp_file = md_file.with_suffix(md_file.suffix + ".tmp")
        tmp_file.write_text(body, encoding="utf-8")
        mdformat.file(tmp_file, options={"wrap": 80})

        formatted_body = tmp_file.read_text(encoding="utf-8")
        tmp_file.unlink()

        formatted_body = formatted_body.replace(dollar_placeholder, "&dollar;")
        for key, val in latex_map.items():
            formatted_body = formatted_body.replace(key, val)
        formatted_body = restore_tooltips(formatted_body, tooltip_map)

        new_text = f"{frontmatter}{formatted_body}" if frontmatter else formatted_body
        md_file.write_text(new_text, encoding="utf-8")

        print(f"  Formatted: {md_file.relative_to(ROOT)}")


def main():
    format_posts()
    BLOG_DIR.mkdir(exist_ok=True)

    md_files = get_post_files()
    if not md_files:
        print("No posts listed in posts/posts.txt")

    posts = []
    for md_file in md_files:
        post = parse_post(md_file)
        posts.append(post)
        out_path = BLOG_DIR / f"{post.slug}.html"
        out_path.write_text(render_post_html(post), encoding="utf-8")
        print(f"  Built: {out_path.relative_to(ROOT)}")

    posts.sort(key=lambda p: p.date, reverse=True)

    index_path = BLOG_DIR / "index.html"
    index_path.write_text(render_index_html(posts), encoding="utf-8")
    print(f"  Built: {index_path.relative_to(ROOT)} ({len(posts)} post(s))")

    build_feed(posts)


if __name__ == "__main__":
    main()
