#!/usr/bin/env python3
"""Build script: converts markdown posts in posts/ to HTML in blog/

Usage: python3 build.py
Requires: pip install -r requirements.txt
"""

import datetime
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import mdformat
    import markdown
    import yaml
    from l2m4m import LaTeX2MathMLExtension
except ImportError:
    print("Missing dependencies. Run: pip install -r requirements.txt", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).parent
POSTS_DIR = ROOT / "posts"
BLOG_DIR = ROOT / "blog"

POST_TEMPLATE = """\
<!-- THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{POST_TITLE}} - Sam Xifaras</title>
    <link rel="stylesheet" href="../styles.css">
    <link rel="stylesheet" href="../blog.css">
    <script src="../theme.js"></script>
</head>
<body>
    <main>
        <div class="container">
            <nav class="blog-nav">
                <a href="../index.html">Home</a>
                <span class="blog-nav-sep">/</span>
                <a href="index.html">Blog</a>
            </nav>
            <div class="theme-switcher">
                <button class="theme-btn" data-theme="normal">Normal</button>
                <button class="theme-btn" data-theme="sepia">Sepia</button>
                <button class="theme-btn" data-theme="dark">Dark</button>
            </div>
            <article class="post">
                <header class="post-header">
                    <h1>{{POST_TITLE}}</h1>
                    <time class="post-date" datetime="{{POST_DATE_ISO}}">{{POST_DATE_DISPLAY}}</time>
                </header>
                <div class="post-body">
                    {{POST_BODY}}
                </div>
            </article>
        </div>
    </main>
    <footer>
        <p>&copy; 2026 Samuel Xifaras</p>
    </footer>
</body>
</html>"""

INDEX_TEMPLATE = """\
<!-- THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - Sam Xifaras</title>
    <link rel="stylesheet" href="../styles.css">
    <link rel="stylesheet" href="../blog.css">
</head>
<body>
    <main>
        <div class="container">
            <nav class="blog-nav">
                <a href="../index.html">Home</a>
                <span class="blog-nav-sep">/</span>
                <span>Blog</span>
            </nav>
            <section class="blog-index">
                <h2>Blog</h2>
                {{POST_LIST}}
            </section>
        </div>
    </main>
    <footer>
        <p>&copy; 2026 Samuel Xifaras</p>
    </footer>
</body>
</html>"""


@dataclass
class PostData:
    title: str
    date: datetime.date
    description: str
    slug: str
    html_body: str


def format_date(d: datetime.date) -> str:
    """Return a human-readable date like 'March 21, 2026'."""
    return d.strftime("%B {day}, %Y").format(day=d.day)


def parse_post(path: Path) -> PostData:
    content = path.read_text(encoding="utf-8")
    parts = content.split("---", 2)
    if len(parts) == 3 and parts[0].strip() == "":
        meta = yaml.safe_load(parts[1]) or {}
        body = parts[2]
    else:
        meta = {}
        body = content

    slug = path.stem
    title = meta.get("title", slug.replace("-", " ").title())
    description = meta.get("description", "")

    raw_date = meta.get("date", "")
    if isinstance(raw_date, datetime.date):
        date = raw_date
    elif raw_date:
        date = datetime.date.fromisoformat(str(raw_date))
    else:
        date = datetime.date.today()

    md = markdown.Markdown(extensions=["fenced_code", "tables", #LaTeX2MathMLExtension()
    ])
    html_body = md.convert(body)

    return PostData(
        title=title,
        date=date,
        description=description,
        slug=slug,
        html_body=html_body,
    )


def render_post_html(post: PostData) -> str:
    return (
        POST_TEMPLATE
        .replace("{{POST_TITLE}}", post.title)
        .replace("{{POST_DATE_ISO}}", post.date.isoformat())
        .replace("{{POST_DATE_DISPLAY}}", format_date(post.date))
        .replace("{{POST_BODY}}", post.html_body)
    )


def render_index_html(posts: list) -> str:
    if not posts:
        post_list = "<p>No posts yet.</p>"
    else:
        entries = []
        for post in posts:
            description_html = (
                f'<p class="post-description">{post.description}</p>'
                if post.description
                else ""
            )
            entries.append(
                f'<article class="post-listing">\n'
                f'    <h3><a href="{post.slug}.html">{post.title}</a></h3>\n'
                f'    <time class="post-date" datetime="{post.date.isoformat()}">'
                f'{format_date(post.date)}</time>\n'
                f'    {description_html}\n'
                f'</article>'
            )
        post_list = "\n".join(entries)

    return INDEX_TEMPLATE.replace("{{POST_LIST}}", post_list)


def format_posts():
    for md_file in sorted(POSTS_DIR.glob("*.md")):
        # Extract frontmatter if present, remove before formatting, and re-add after
        text = md_file.read_text(encoding="utf-8")
        import re

        match = re.match(r"^---\s*\n(.*?)(?:^---\s*$\n?)", text, re.DOTALL | re.MULTILINE)
        if match:
            frontmatter = match.group(0)
            body = text[len(frontmatter):]
            # Remove any leading newlines after the frontmatter block
            body = body.lstrip('\r\n')
        else:
            frontmatter = ""
            body = text

        tmp_file = md_file.with_suffix(md_file.suffix + ".tmp")
        tmp_file.write_text(body, encoding="utf-8")
        mdformat.file(tmp_file, options={"wrap": 80})

        formatted_body = tmp_file.read_text(encoding="utf-8")
        tmp_file.unlink()

        new_text = f"{frontmatter}{formatted_body}" if frontmatter else formatted_body
        md_file.write_text(new_text, encoding="utf-8")

        print(f"  Formatted: {md_file.relative_to(ROOT)}")


def main():
    format_posts()
    BLOG_DIR.mkdir(exist_ok=True)

    md_files = sorted(POSTS_DIR.glob("*.md"), reverse=True)
    if not md_files:
        print("No markdown files found in posts/")

    posts = []
    for md_file in md_files:
        post = parse_post(md_file)
        posts.append(post)
        out_path = BLOG_DIR / f"{post.slug}.html"
        out_path.write_text(render_post_html(post), encoding="utf-8")
        print(f"  Built: {out_path.relative_to(ROOT)}")

    posts.sort(key=lambda p: p.date, reverse=True)

    index_path = BLOG_DIR / "index.html"
    index_path.write_text(render_index_html(posts), encoding="utf-8")
    print(f"  Built: {index_path.relative_to(ROOT)} ({len(posts)} post(s))")


if __name__ == "__main__":
    main()
