#!/usr/bin/env python3
"""Build script: converts markdown posts in posts/ to HTML in blog/

Usage: python3 build.py
Requires: pip install -r requirements.txt
"""

import datetime
import re
import sys
from dataclasses import dataclass
from pathlib import Path

try:
    import mdformat
    import markdown
    import yaml
    from l2m4m import LaTeX2MathMLExtension
except ImportError:
    print("Missing dependencies. Run: pip install -r requirements.txt", file=sys.stderr)
    sys.exit(1)

from tooltip import TooltipExtension, preserve_tooltips, restore_tooltips, add_tooltip_footnotes
from rss import build_feed

ROOT = Path(__file__).parent
POSTS_DIR = ROOT / "posts"
BLOG_DIR = ROOT / "blog"
TOPICS_DIR = BLOG_DIR / "topics"
POSTS_LIST = POSTS_DIR / "posts.txt"

TOPICS = ["tech", "philosophy", "personal"]
TOPIC_LABELS = {"tech": "Tech", "philosophy": "Philosophy", "personal": "Personal"}
DEFAULT_TOPIC = "personal"

POST_TEMPLATE = """\
<!-- THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{POST_TITLE}} - Sam Xifaras</title>
    <link rel="stylesheet" href="../../../styles.css">
    <link rel="stylesheet" href="../../../blog.css">
    <script src="../../../theme.js"></script>
    <script src="../../../analytics.js"></script>
</head>
<body>
    <main>
        <div class="container">
            <a href="../../../feed.xml" class="rss-corner" title="RSS Feed" aria-label="RSS Feed"><img src="../../../rssicon.svg" width="24" height="24" alt="RSS Feed"></a>
            <nav class="blog-nav">
                <a href="../../../index.html">Home</a>
                <span class="blog-nav-sep">/</span>
                <a href="../../index.html">Blog</a>
                <span class="blog-nav-sep">/</span>
                <a href="index.html">{{TOPIC_LABEL}}</a>
            </nav>
            <div class="theme-switcher">
                <button class="theme-btn" data-theme="normal">Normal</button>
                <button class="theme-btn" data-theme="sepia">Sepia</button>
                <button class="theme-btn" data-theme="dark">Dark</button>
            </div>
            <article class="post">
                <header class="post-header">
                    <h1>{{POST_TITLE}}</h1>
                    <time class="post-date" datetime="{{POST_DATE_ISO}}">{{POST_DATE_DISPLAY}}</time>
                </header>
                <div class="post-body">
                    {{POST_BODY}}
                </div>
            </article>
        </div>
    </main>
    <footer>
        <div class="newsletter">
            <p class="newsletter-label">Want to get updates from me? Drop your email below!</p>
            <form id="newsletter-form" class="newsletter-form">
                <input type="email" id="newsletter-email" placeholder="your@email.com" required>
                <button type="submit">Subscribe</button>
            </form>
            <p id="newsletter-msg" class="newsletter-msg"></p>
        </div>
        <p class="footer-copyright">&copy; 2026 Samuel Xifaras</p>
    </footer>
</body>
</html>"""

INDEX_TEMPLATE = """\
<!-- THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog - Sam Xifaras</title>
    <link rel="stylesheet" href="../styles.css">
    <link rel="stylesheet" href="../blog.css">
    <script src="../theme.js"></script>
    <script src="../analytics.js"></script>
</head>
<body>
    <main>
        <div class="container">
            <a href="../feed.xml" class="rss-corner" title="RSS Feed" aria-label="RSS Feed"><img src="../rssicon.svg" width="24" height="24" alt="RSS Feed"></a>
            <nav class="blog-nav">
                <a href="../index.html">Home</a>
                <span class="blog-nav-sep">/</span>
                <span>Blog</span>
            </nav>
            <div class="theme-switcher">
                <button class="theme-btn" data-theme="normal">Normal</button>
                <button class="theme-btn" data-theme="sepia">Sepia</button>
                <button class="theme-btn" data-theme="dark">Dark</button>
            </div>
            <section class="blog-index">
                <i id="expressions">Expressions of my inner world</i>
                <p>Find some of these writings and more on my <a href="https://samxif.substack.com/">Substack</a></p>
                <h2>Blog</h2>
                <div class="topic-nav">
                    <span class="topic-nav-label">Topics:</span>
                    <a href="topics/tech/index.html" data-tip="Software, AI, and the industry.">Tech</a>
                    <a href="topics/philosophy/index.html" data-tip="Ways of thinking and being.">Philosophy</a>
                    <a href="topics/personal/index.html" data-tip="Catch-all for personal reflections and creative writing.">Personal</a>
                </div>
                <div class="format-nav">
                    <span class="format-nav-label">Format:</span>
                    <button class="filter-btn active" data-filter="all">All</button>
                    <button class="filter-btn" data-filter="blog" data-tip="Longer-form, more heavily researched content.">Blog</button>
                    <button class="filter-btn" data-filter="thoughts" data-tip="Quick, unedited streams of consciousness.">Thoughts</button>
                    <button class="filter-btn" data-filter="poetry" data-tip="Self-explanatory.">Poetry</button>
                </div>
                {{POST_LIST}}
            </section>
        </div>
    </main>
    <footer>
        <div class="newsletter">
            <p class="newsletter-label">Want to get updates from me? Drop your email below!</p>
            <form id="newsletter-form" class="newsletter-form">
                <input type="email" id="newsletter-email" placeholder="your@email.com" required>
                <button type="submit">Subscribe</button>
            </form>
            <p id="newsletter-msg" class="newsletter-msg"></p>
        </div>
        <p class="footer-copyright">&copy; 2026 Samuel Xifaras</p>
    </footer>
    <script src="../filters.js"></script>
</body>
</html>"""

TOPIC_TEMPLATE = """\
<!-- THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{TOPIC_LABEL}} - Sam Xifaras</title>
    <link rel="stylesheet" href="../../../styles.css">
    <link rel="stylesheet" href="../../../blog.css">
    <script src="../../../theme.js"></script>
    <script src="../../../analytics.js"></script>
</head>
<body>
    <main>
        <div class="container">
            <a href="../../../feed.xml" class="rss-corner" title="RSS Feed" aria-label="RSS Feed"><img src="../../../rssicon.svg" width="24" height="24" alt="RSS Feed"></a>
            <nav class="blog-nav">
                <a href="../../../index.html">Home</a>
                <span class="blog-nav-sep">/</span>
                <a href="../../index.html">Blog</a>
                <span class="blog-nav-sep">/</span>
                <span>{{TOPIC_LABEL}}</span>
            </nav>
            <div class="theme-switcher">
                <button class="theme-btn" data-theme="normal">Normal</button>
                <button class="theme-btn" data-theme="sepia">Sepia</button>
                <button class="theme-btn" data-theme="dark">Dark</button>
            </div>
            <section class="blog-index">
                <h2>{{TOPIC_LABEL}}</h2>
                <div class="topic-nav">
                    <span class="topic-nav-label">Topics:</span>
                    {{TOPIC_NAV_LINKS}}
                </div>
                <div class="format-nav">
                    <span class="format-nav-label">Format:</span>
                    <button class="filter-btn active" data-filter="all">All</button>
                    <button class="filter-btn" data-filter="blog" data-tip="Longer-form, more heavily researched content.">Blog</button>
                    <button class="filter-btn" data-filter="thoughts" data-tip="Quick, unedited streams of consciousness.">Thoughts</button>
                    <button class="filter-btn" data-filter="poetry" data-tip="Self-explanatory.">Poetry</button>
                </div>
                {{POST_LIST}}
            </section>
        </div>
    </main>
    <footer>
        <div class="newsletter">
            <p class="newsletter-label">Want to get updates from me? Drop your email below!</p>
            <form id="newsletter-form" class="newsletter-form">
                <input type="email" id="newsletter-email" placeholder="your@email.com" required>
                <button type="submit">Subscribe</button>
            </form>
            <p id="newsletter-msg" class="newsletter-msg"></p>
        </div>
        <p class="footer-copyright">&copy; 2026 Samuel Xifaras</p>
    </footer>
    <script src="../../../filters.js"></script>
</body>
</html>"""

REDIRECT_TEMPLATE = """\
<!-- THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY -->
<!-- Backwards-compat stub: this post has moved to {{NEW_URL}} -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{POST_TITLE}} - Sam Xifaras</title>
    <link rel="canonical" href="{{NEW_URL}}">
    <meta http-equiv="refresh" content="0; url={{NEW_URL}}">
</head>
<body>
    <p>This post has moved. <a href="{{NEW_URL}}">Click here</a> if you are not redirected.</p>
</body>
</html>"""


@dataclass
class PostData:
    title: str
    date: datetime.date
    description: str
    slug: str
    html_body: str
    category: str = "blog"
    topic: str = DEFAULT_TOPIC


def format_date(d: datetime.date) -> str:
    """Return a human-readable date like 'March 21, 2026'."""
    return d.strftime("%B {day}, %Y").format(day=d.day)


def parse_post(path: Path) -> PostData:
    content = path.read_text(encoding="utf-8")
    parts = content.split("---", 2)
    if len(parts) == 3 and parts[0].strip() == "":
        meta = yaml.safe_load(parts[1]) or {}
        body = parts[2]
    else:
        meta = {}
        body = content

    slug = path.stem
    title = meta.get("title", slug.replace("-", " ").title())
    description = meta.get("description", "")
    category = meta.get("category", "blog")
    topic = meta.get("topic", DEFAULT_TOPIC)
    if topic not in TOPICS:
        print(f"  Warning: {path.name} has unknown topic '{topic}', defaulting to '{DEFAULT_TOPIC}'", file=sys.stderr)
        topic = DEFAULT_TOPIC

    raw_date = meta.get("date", "")
    if isinstance(raw_date, datetime.date):
        date = raw_date
    elif raw_date:
        date = datetime.date.fromisoformat(str(raw_date))
    else:
        date = datetime.date.today()

    md = markdown.Markdown(extensions=["fenced_code", "tables", LaTeX2MathMLExtension(), TooltipExtension()])
    html_body = add_tooltip_footnotes(md.convert(body))

    return PostData(
        title=title,
        date=date,
        description=description,
        slug=slug,
        html_body=html_body,
        category=category,
        topic=topic,
    )


def render_post_html(post: PostData) -> str:
    return (
        POST_TEMPLATE
        .replace("{{POST_TITLE}}", post.title)
        .replace("{{POST_DATE_ISO}}", post.date.isoformat())
        .replace("{{POST_DATE_DISPLAY}}", format_date(post.date))
        .replace("{{TOPIC_LABEL}}", TOPIC_LABELS.get(post.topic, post.topic))
        .replace("{{POST_BODY}}", post.html_body)
    )


def render_post_listing_entries(posts: list, post_url_fn, topic_url_fn) -> str:
    if not posts:
        return "<p>No posts yet.</p>"
    entries = []
    for post in posts:
        description_html = (
            f'<p class="post-description">{post.description}</p>'
            if post.description
            else ""
        )
        topic_label = TOPIC_LABELS.get(post.topic, post.topic)
        entries.append(
            f'<article class="post-listing" data-category="{post.category}" data-topic="{post.topic}">\n'
            f'    <h3><a href="{post_url_fn(post)}">{post.title}</a></h3>\n'
            f'    <div class="post-meta">'
            f'<time class="post-date" datetime="{post.date.isoformat()}">'
            f'{format_date(post.date)}</time>'
            f'<span class="post-category">{post.category}</span>'
            f'<a class="post-topic" href="{topic_url_fn(post.topic)}">{topic_label}</a>'
            f'</div>\n'
            f'    {description_html}\n'
            f'</article>'
        )
    return "\n".join(entries)


def render_index_html(posts: list) -> str:
    post_list = render_post_listing_entries(
        posts,
        post_url_fn=lambda p: f"topics/{p.topic}/{p.slug}.html",
        topic_url_fn=lambda t: f"topics/{t}/index.html",
    )
    return INDEX_TEMPLATE.replace("{{POST_LIST}}", post_list)


def render_topic_html(topic: str, posts: list) -> str:
    label = TOPIC_LABELS[topic]
    other_topics = []
    for t in TOPICS:
        if t == topic:
            other_topics.append(f'<span class="topic-nav-current">{TOPIC_LABELS[t]}</span>')
        else:
            other_topics.append(f'<a href="../{t}/index.html">{TOPIC_LABELS[t]}</a>')
    topic_nav_links = "\n                    ".join(other_topics)
    # Posts on a topic page live in the same folder as the topic index.
    post_list = render_post_listing_entries(
        posts,
        post_url_fn=lambda p: f"{p.slug}.html",
        topic_url_fn=lambda t: "index.html" if t == topic else f"../{t}/index.html",
    )
    return (
        TOPIC_TEMPLATE
        .replace("{{TOPIC_LABEL}}", label)
        .replace("{{TOPIC_SLUG}}", topic)
        .replace("{{TOPIC_NAV_LINKS}}", topic_nav_links)
        .replace("{{POST_LIST}}", post_list)
    )


def get_post_files() -> list[Path]:
    """Return the list of post files to build, as specified in posts/posts.txt."""
    lines = POSTS_LIST.read_text(encoding="utf-8").splitlines()
    paths = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        name = line if line.endswith(".md") else f"{line}.md"
        path = POSTS_DIR / name
        if path.exists():
            paths.append(path)
        else:
            print(f"  Warning: {name} listed in posts.txt but not found", file=sys.stderr)
    return paths


def format_posts():
    for md_file in sorted(POSTS_DIR.glob("*.md")):
        # Extract frontmatter if present, remove before formatting, and re-add after
        text = md_file.read_text(encoding="utf-8")
        match = re.match(r"^---\s*\n(.*?)(?:^---\s*$\n?)", text, re.DOTALL | re.MULTILINE)
        if match:
            frontmatter = match.group(0)
            body = text[len(frontmatter):]
            # Remove any leading newlines after the frontmatter block
            body = body.lstrip('\r\n')
        else:
            frontmatter = ""
            body = text

        tooltip_map = {}
        body = preserve_tooltips(body, tooltip_map)

        latex_map = {}
        def replace_latex(m):
            key = f"XLATEX{len(latex_map)}X"
            latex_map[key] = m.group(0)
            return key
        body = re.sub(r'\$\$[\s\S]*?\$\$|\$[^$\n]+?\$', replace_latex, body, flags=re.MULTILINE)

        dollar_placeholder = "XDOLLARENTITYX"
        body = body.replace("&dollar;", dollar_placeholder)

        tmp_file = md_file.with_suffix(md_file.suffix + ".tmp")
        tmp_file.write_text(body, encoding="utf-8")
        mdformat.file(tmp_file, options={"wrap": 80})

        formatted_body = tmp_file.read_text(encoding="utf-8")
        tmp_file.unlink()

        formatted_body = formatted_body.replace(dollar_placeholder, "&dollar;")
        for key, val in latex_map.items():
            formatted_body = formatted_body.replace(key, val)
        formatted_body = restore_tooltips(formatted_body, tooltip_map)

        new_text = f"{frontmatter}{formatted_body}" if frontmatter else formatted_body
        md_file.write_text(new_text, encoding="utf-8")

        print(f"  Formatted: {md_file.relative_to(ROOT)}")


def cleanup_stale_outputs():
    """Clear backwards-compat redirect stubs and old flat topic-listing files so they get regenerated cleanly.

    Anything in blog/ other than index.html is treated as a regenerable redirect stub.
    Anything in blog/topics/ at the file level (vs. a per-topic subdir) is a stale flat topic page.
    """
    if BLOG_DIR.exists():
        for html in BLOG_DIR.glob("*.html"):
            if html.name != "index.html":
                html.unlink()
    if TOPICS_DIR.exists():
        for html in TOPICS_DIR.glob("*.html"):
            html.unlink()


def render_redirect_stub(post: PostData) -> str:
    new_url = f"topics/{post.topic}/{post.slug}.html"
    return (
        REDIRECT_TEMPLATE
        .replace("{{POST_TITLE}}", post.title)
        .replace("{{NEW_URL}}", new_url)
    )


def main():
    format_posts()
    BLOG_DIR.mkdir(exist_ok=True)
    cleanup_stale_outputs()

    published_slugs = {p.stem for p in get_post_files()}

    all_md_files = sorted(POSTS_DIR.glob("*.md"), reverse=True)
    if not all_md_files:
        print("No markdown files found in posts/")

    all_posts = []
    published_posts = []
    for md_file in all_md_files:
        post = parse_post(md_file)
        all_posts.append(post)
        topic_dir = TOPICS_DIR / post.topic
        topic_dir.mkdir(parents=True, exist_ok=True)
        out_path = topic_dir / f"{post.slug}.html"
        out_path.write_text(render_post_html(post), encoding="utf-8")
        print(f"  Built: {out_path.relative_to(ROOT)}")
        if post.slug in published_slugs:
            published_posts.append(post)

    published_posts.sort(key=lambda p: p.date, reverse=True)

    index_path = BLOG_DIR / "index.html"
    index_path.write_text(render_index_html(published_posts), encoding="utf-8")
    print(f"  Built: {index_path.relative_to(ROOT)} ({len(published_posts)} post(s))")

    for topic in TOPICS:
        topic_dir = TOPICS_DIR / topic
        topic_dir.mkdir(parents=True, exist_ok=True)
        topic_posts = [p for p in published_posts if p.topic == topic]
        topic_path = topic_dir / "index.html"
        topic_path.write_text(render_topic_html(topic, topic_posts), encoding="utf-8")
        print(f"  Built: {topic_path.relative_to(ROOT)} ({len(topic_posts)} post(s))")

    # Backwards-compat redirect stubs at the previous URLs.
    for post in all_posts:
        stub_path = BLOG_DIR / f"{post.slug}.html"
        stub_path.write_text(render_redirect_stub(post), encoding="utf-8")
        print(f"  Redirect: {stub_path.relative_to(ROOT)} -> topics/{post.topic}/{post.slug}.html")

    build_feed(published_posts)


if __name__ == "__main__":
    main()
